config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  resources :trainings
  resources :playgrounds
  resources :playgrounds do
    member do
      get 'check_favorite'
    end
  end
  resources :favorite_playgrounds do
    post :add_to_favorites, on: :collection
  end
  resources :favorite_playgrounds, only: [:create, :destroy]
  resources :profils do
    member do
      post 'follow'
      delete 'unfollow'
    end
  end
  get 'pages/zone_info/:id', to: 'pages#zone_info', as: 'zone_info_page'
  resources :notifs, only: [:destroy]
  resources :leaderboards, only: [:index] do
    collection do
      get :filter_by_zone
      get :index_filtered
    end
  end
  get 'pages/stats', to: 'pages#stats', as: 'stats_page'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/playground.rb
class Playground < ApplicationRecord
  has_many :trainings
  has_many :favorite_playgrounds
  has_many :users, through: :favorite_playgrounds
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/controllers/playgrounds_controller.rb
class PlaygroundsController < ApplicationController
  def index
    @playgrounds = Playground.all
    # The `geocoded` scope filters only flats with coordinates
    @markers = @playgrounds.geocoded.map do |playground|
      {
        lat: playground.latitude,
        lng: playground.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { playground: playground }, class: "shadow"),
        marker_html: if current_user.favorite_playgrounds.present? && playground == current_user.favorite_playgrounds.first.playground
                       render_to_string(partial: "markerfavorite")
                     else
                       render_to_string(partial: "marker")
                     end
      }
    end
  end

  def show
    @playground = Playground.find(params[:id])
    @playground_leaderboard = calculate_playground_leaderboard(@playground)
  end

  private

  def calculate_playground_leaderboard(playground)
    filtered_trainings = get_filtered_trainings(playground)

    best_trainings = filtered_trainings.sort_by do |training|
      -shooting_efficiency(training)
    end

    # Return the calculated leaderboard information
    best_trainings
  end

  def get_filtered_trainings(playground)
    if params[:zone_id].present?
      playground.trainings.where(zone_id: params[:zone_id])
    else
      playground.trainings
    end
  end

  def shooting_efficiency(training)
    return 0 if training.shot_total.zero?

    (training.shot_made.to_f / training.shot_total) * 100
  end
end

app/views/playgrounds/_info_window.html.erb
<style>
  .custom-link {
    text-decoration: none;
    color: white; /* Change la couleur du texte des liens */
  }
  .playground-name {
    color: #FF3115; /* Change la couleur du texte du nom du terrain */
  }
  :focus {
    outline: none;
  }
  .info-content {
    display: flex;
    align-items: center; /* Aligne le texte au centre avec l'image */
  }
  .info-content img {
    width: 80px;
    height: 80px;
    object-fit: cover;
    margin-right: 10px;
  }

  .info-window {
  position: relative; /* Ajoute une position relative à la fenêtre d'information */
}

.favorite-button {
  position: absolute; /* Positionne le bouton "Favori" absolument par rapport à la fenêtre d'information */
  top: 0; /* Positionne le bouton "Favori" en haut */
  left: 0; /* Positionne le bouton "Favori" à droite */
}

.favorite-button .btn {
  padding: 0; /* Supprime le padding du bouton */
  margin: 0; /* Supprime la marge du bouton */
}

.favorite-button .fas {
  padding: 0; /* Supprime le padding de l'icône */
  margin: 0; /* Supprime la marge de l'icône */
}

.favorite-form {
  margin-left: 2px; /* Décale le formulaire légèrement vers la droite */
  margin-top: 3px; /* Décale le formulaire légèrement vers le bas */
}

.favorite-button a {
  margin-left: 7px; /* Décale le lien de l'étoile rouge légèrement vers la droite */
}
</style>

<h2 class="text-decoration-none text-dark pt-1" style="margin-bottom: 20px; margin-top: 20px;"><strong><%= link_to "#{playground.name}", playground_path(playground), class: "custom-link playground-name", style: "text-decoration: underline;" %></strong></h2>

<div class="info-content">
  <img src="<%= playground.court %>" alt="Playground Picture">
  <h6 class="text-white"><strong><%= link_to "#{playground.address}", playground_path(playground), class: "custom-link" %></strong></h3>
</div>

<div class="favorite-button">
<div class= "favorite-form">
  <% if current_user.favorite_playgrounds.map(&:playground_id).include?(playground.id) %>
    <%= link_to "<i class='fas fa-star' style='color: #FF3115; padding-top: 5px;'></i>".html_safe, favorite_playground_path(playground), class: "fa-2x ps-1 etoile", data: { turbo_method: :delete }%>
    </div>
  <% else %>
    <%= simple_form_for FavoritePlayground.new, remote: true, html: { class: "favorite-form" } do |f| %>
  <%= f.hidden_field :playground_id, value: playground.id %>
  <%= f.submit "", class: "btn btn-link", style: "background: transparent; border: none; position: absolute; width: 100%; height: 100%; z-index: 1;" %>
  <span class="fa-stack" style="font-size: 1.1em; position: relative;">
    <i class="fas fa-star fa-stack-1x" style="color: #3c3c44; padding-top: 5px;"></i>
    <i class="far fa-star fa-2x" style="color: #FF3115; padding-top: 5px;"></i>
  </span>
<% end %>
  <% end %>
</div>

app/views/playgrounds/_leaderboard_filter.html.erb
<div class="d-flex" style="width: 100%;">
  <%= form_tag(playground_path(@playground), method: :get, class: "mb-4") do %>
    <div class="form-group d-flex justify-content-start">
          <%= label_tag "user_id", "" %>
          <%= text_field_tag :username, params[:username], placeholder: "Nom", class: "form-control", style: "width: 35%; margin-left: 10px;" %>
          <%= label_tag "zone_id", "" %>
          <%= select_tag(:zone_id, options_for_select([["Tout", ""], ["Raquette", 1], ["Lancer franc", 2], ["3 points de face", 3], ["2 points fond droite", 4], ["3 points fond droite", 5], ["2 points angle droite", 6], ["3 points angle droite", 7], ["2 points fond gauche", 8], ["3 points fond gauche", 9], ["2 points fond gauche", 10], ["3 points angle gauche", 11]], params[:zone_id]), class: "form-control", style: "width: 25%; margin-left: 10px;") %>
          <%= submit_tag("Filtrer", class: "custom-button") %>
          <%= link_to '<i class="fas fa-xmark fa-1x"></i>'.html_safe, leaderboards_path, class: "custom-button me-2" %>
  <% end %>
</div>

<div class="d-flex justify-content-center align-item-center mb-5 pb-5">
  <table class="table table-striped rounded-table">
    <thead class="fs-3">
      <tr class="text-center">
        <th scope="col" class="py-2"><strong>Rang</strong></th>
        <th scope="col" class="py-2"><strong>Nom</strong></th>
        <th scope="col" class="py-2"><strong>Zone</strong></th>
        <th scope="col" class="py-2"><strong>Précision</strong></th>
      </tr>
    </thead>
    <tbody>
      <% @profiles.each_with_index do |user, index| %>
        <tr class="text-center">
          <th scope="row"><%= index + 1 %></th>
          <td><%= link_to "#{user.username}", profil_path(user), class:"text-dark text-decoration-none" %></td>
          <% if params[:zone_id].present? %>
            <td><%= Zone.find(params[:zone_id]).name %></td>
          <% else %>
            <td><strong>All</strong></td>
          <% end %>
          <% if params[:zone_id].present? %>
            <td><strong><%= user.average_shooting_efficiency_by_zone(params[:zone_id]).round(1) %> %</strong></td>
          <% else %>
            <td><strong><%= user.average_shooting_efficiency.round(1) %> %</strong></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>

app/views/playgrounds/_marker.html.erb
<%= image_tag "icons/basket_map.svg", height: 65, width: 65, alt: "Logo" %>

app/views/playgrounds/_markerfavorite.html.erb
<%= image_tag "icons/basket_map_fav.svg", height: 65, width: 65, alt: "Logo", style: "color: #FF3115;" %>

app/views/playgrounds/_playground_leaderboard.html.erb
<h1>Playground Leaderboard</h1>

<table class="table table-striped rounded-table">
  <thead class="fs-3">
    <tr class="text-center">
      <th scope="col" class="py-2"><strong>Rang</strong></th>
      <th scope="col" class="py-2"><strong>Nom</strong></th>
      <th scope="col" class="py-2"><strong>Zone</strong></th>
      <th scope="col" class="py-2"><strong>Précision</strong></th>
    </tr>
  </thead>
  <tbody>
    <% @playground_leaderboard.each_with_index do |training, index| %>
      <tr class="text-center">
        <th scope="row"><%= index + 1 %></th>
        <td><%= link_to "#{training.user.username}", profil_path(training.user), class:"text-dark text-decoration-none" %></td>
        <td><strong><%= training.zone.name %></strong></td>
        <td><strong><%= (training.shooting_efficiency).round(1) %>%</strong></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/playgrounds/index.html.erb
<div style="position: fixed; top: 0; width: 100%; z-index: 1000;">
  <%= render 'shared/navbar' %>
</div>

<div style="height: 100vh;"
  data-controller="map"
  data-map-markers-value="<%= @markers.to_json %>"
  data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
</div>

<div style="position: fixed; bottom: 0; width: 100%; z-index: 1000;">
  <%= render 'shared/footnav' %>
</div>

app/views/playgrounds/show.html.erb
<%= render "shared/navbar" %>
<div class="container mt-1">
  <img class="carte-jouer shadow" src="<%= @playground.court %>" alt="Playground Picture" style="max-width: 100%; height: auto;">

  <div class="carte-jouer mt-4 mb-3 py-3 bg-white text-dark text-center shadow">
      <h1 style="color: #FF3115;"><%= @playground.name %></h1>
      <h2><%= @playground.address %></h2>
  </div>
</div>


<h1 class="text-center"><strong>Classement</strong></h1>
<div class="mb-5 pb-5">
  <table class="table table-striped">
  <thead class="fs-3">
    <tr class="text-center">
      <th scope="col" class="py-2"><strong>Rang</strong></th>
      <th scope="col" class="py-2"><strong>Nom</strong></th>
      <th scope="col" class="py-2"><strong>Zone</strong></th>
      <th scope="col" class="py-2"><strong>Précision</strong></th>
    </tr>
  </thead>
  <tbody>
    <% @playground_leaderboard.each_with_index do |training, index| %>
      <tr class="text-center">
        <th scope="row" class="<%= top_players_class(index) %>"><%= index + 1 %></th>
        <td class="<%= top_players_class(index) %>"><%= link_to "#{training.user.username}", profil_path(training.user), class:"text-dark text-decoration-none #{top_players_class(index)}" %></td>
        <td class="<%= top_players_class(index) %>"><strong><%= training.zone.name %></strong></td>
        <td class="<%= top_players_class(index) %>"><strong><%= (training.shooting_efficiency).round(1) %>%</strong></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<div style="position: fixed; bottom: 0; width: 100%;">
  <%= render 'shared/footnav' %>
</div>