config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "pages#home"
  resources :trainings
  resources :playgrounds
  resources :playgrounds do
    member do
      get 'check_favorite'
    end
  end
  resources :favorite_playgrounds do
    post :add_to_favorites, on: :collection
  end
  resources :favorite_playgrounds, only: [:create, :destroy]
  resources :profils do
    member do
      post 'follow'
      delete 'unfollow'
    end
  end
  get 'pages/zone_info/:id', to: 'pages#zone_info', as: 'zone_info_page'
  resources :notifs, only: [:destroy]
  resources :leaderboards, only: [:index] do
    collection do
      get :filter_by_zone
      get :index_filtered
    end
  end
  get 'pages/stats', to: 'pages#stats', as: 'stats_page'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1 custom-alert" role="alert">
    <button type="button" class="btn-close custom-close-button" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1 custom-alert" role="alert">
    <button type="button" class="btn-close custom-close-button" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footnav.html.erb
<div class="general" data-controller="foot">
  <div class="navigation">
    <ul id="ul1">
      <li class="list <%= 'active' if (controller_name == 'playgrounds') %>">
        <%= link_to playgrounds_path, data: { foot_target: 'link' } do %>
          <span class="icon ">
            <ion-icon name="map-outline"></ion-icon>
          </span>
          <span class="texte">Terrains</span>
        <% end %>
      </li>
      <li class="list <%= 'active' if controller_name == 'leaderboards' %>">
        <%= link_to leaderboards_path, data: { foot_target: 'link' } do %>
          <span class="icon">
            <ion-icon name="medal-outline"></ion-icon>
          </span>
          <span class="texte">Classement</span>
        <% end %>
      </li>
      <li class="list <%= 'active' if (controller_name == 'pages' && action_name == 'home') %>">
        <%= link_to root_path, data: { foot_target: 'link' } do %>
          <span class="icon">
            <ion-icon name="basketball-outline"></ion-icon>
          </span>
          <span class="texte">Accueil</span>
        <% end %>
      </li>
      <li class="list <%= 'active' if (controller_name == 'pages' && action_name == 'stats') %>">
        <%= link_to stats_page_path(current_user), data: { foot_target: 'link' } do %>
          <span class="icon">
            <ion-icon name="stats-chart-outline"></ion-icon>
          </span>
          <span class="texte">Stats</span>
        <% end %>
      </li>
      <li class="list <%= 'active' if (controller_name == 'profils' || controller_name == 'trainings') %>">
        <%= link_to profil_path(current_user), data: { foot_target: 'link' } do %>
          <span class="icon">
            <ion-icon name="person-outline"></ion-icon>
          </span>
          <span class="texte">Profil</span>
        <% end %>
      </li>
      <div class="indicator"></div>
    </ul>
  </div>
</div>

<script>
  const list = document.querySelectorAll(".list");
  function activeLink() {
    list.forEach((item) =>
      item.classList.remove("active"));
    this.classList.add("active");
  }
  list.forEach((item) =>
    item.addEventListener("click", activeLink));
</script>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon" style="background: transparent;">
  <div class="container-fluid d-flex justify-content-center">
    <%= link_to root_path, class: "navbar-brand d-flex justify-content-center" do %>
      <%= image_tag "canyouscore.svg", class: "navbar-logo" %>
    <% end %>
    <div class="notif">
      <% if user_signed_in? %>
        <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNotif" aria-controls="navbarNotif" aria-expanded="false" aria-label="Toggle navigation">
          <div class="position-relative">
            <span class="fas fa-bell"></span>
            <% if current_user.followee_notifs.present? %>
              <div class="pastille"></div>
            <% end %>
          </div>
        </button>

        <div class="collapse navbar-collapse mt-4 pt-2" id="navbarNotif">
          <ul class="navbar-nav me-auto">
            <li class="nav-item">
              <% current_user.followee_notifs.where(follow: current_user).take(3).each do |n| %>
                  <div class="notification shadow">
                    <% if n.user.photo.attached? == true  %>
                      <%= link_to profil_path(n.user_id) do %>
                        <%= cl_image_tag n.user.photo.key, class: "avatar-large" %>
                      <% end %>
                    <% else %>
                      <%= link_to profil_path(n.user_id) do %>
                        <%= cl_image_tag("uk7594qzhdhrmsmdfnbb", class: "avatar-large" ) %>
                      <% end %>
                    <% end %>
                    <div class="notification-content">
                      <p><small>Session du <%= n.training.created_at.strftime("%d/%m/%y") %></small></p>
                      <p><%= n.user.username %> a shooté à <%= n.training.shooting_efficiency.to_i %>%</p>
                    </div>
                    <div class="notification-actions">
                      <%= link_to '<i class="far fa-trash-alt"></i>'.html_safe, notif_path(n), data: { turbo_method: :delete } %>
                    </div>
                  </div>
              <% end %>
            </li>
          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_navtrain.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon position-absolute">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Profil", profil_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Statistiques", stats_page_path(current_user), class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Classement", leaderboards_path, class: "nav-link" %>
          </li>
          <hr>
          <li class="nav-item">
            <%= link_to "Déconnexion", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Connexion", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>